name: denteeth
description: App do Socorrista.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  cloud_functions: ^4.3.0
  firebase_storage: ^11.2.0
  cloud_firestore: ^4.7.0
  camera:
  gallery_saver: ^2.3.2
  path_provider:
  path:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/telaInicio.png

