name: denteeth
description: App do Socorrista.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  uuid: ^3.0.6
  cupertino_icons: ^1.0.2
  firebase_core: ^2.12.0
  cloud_functions: ^4.3.0
  firebase_storage: ^11.2.0
  cloud_firestore: ^4.7.0
  camera:
  gallery_saver: ^2.3.2
  path_provider:
  path:
  google_fonts: ^4.0.4
  firebase_messaging: ^14.6.2
  google_maps_flutter: ^2.3.0
  location: ^4.4.0
  app_settings: ^4.2.0
  fluttertoast: ^8.2.2
  connectivity_plus: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'images/icon.png'
  adaptive_icon_background: 'images/icon.png'
  adaptive_icon_foreground: 'images/icon.png'

flutter:

  uses-material-design: true

  assets:
    - images/telaInicio.png
    - images/telefone.png
    - images/aguardando.png

